### ISSUE TITLE
Animación en Blender

### ISSUE THREAD

**Issue by Band-hi** [SistemasTecTlaxiaco/actividad-6-realidad-aumentada-de-objeto-3d-con-animacion-remi-team-1#1]
[Reporte 4 - Animación en Blender.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-realidad-aumentada-de-objeto-3d-con-animacion-remi-team-1/files/11107351/Reporte.4.-.Animacion.en.Blender.pdf)

**Comment by Yabin-2021** [comment]
Calificación: 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
